apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Meshlium Gateway Plugin
  description: Meshlium Gateway Plugin for the Reekoh IoT Platform. Enables the platform to ingest data for Libelium's Meshlium via MQTT Protocol
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - gateway
    - meshlium
  config:
    user:
      label: User
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) The username to use if you want to authenticate incoming traffic."
    password:
      label: Password
      type: Password
      maxLength: 1000
      required: false
      help: "(Optional) The password to use if you want to authenticate incoming traffic."
    topic:
      label: Topic
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) The topic to listen to for device data. Default libelium/data."

  loadBalancing:
    method: http
    enableSticky: true

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??